# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adaptive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DD', models.IntegerField(max_length=200)),
                ('DefectLeakage', models.IntegerField(max_length=200)),
                ('DefectRejection', models.IntegerField(max_length=200)),
                ('TestCaseCount', models.IntegerField(max_length=200)),
                ('ApplicationComplexity', models.IntegerField(max_length=200)),
                ('DomainKnowledge', models.IntegerField(max_length=200)),
                ('TechnicalSkills', models.IntegerField(max_length=200)),
                ('ReqQueryCount', models.IntegerField(max_length=200)),
                ('CodeReviewComments', models.IntegerField(max_length=200)),
                ('DesignReviewComments', models.IntegerField(max_length=200)),
                ('NoofResources', models.IntegerField(max_length=200)),
                ('BudgetinUse', models.IntegerField(max_length=200)),
                ('ETA', models.IntegerField(max_length=200)),
                ('CostofResource', models.IntegerField(max_length=200)),
                ('Efficiency', models.IntegerField(max_length=200)),
                ('ProjectStatus', models.IntegerField(max_length=200)),
                ('AvailabilityofBudget', models.IntegerField(max_length=200)),
            ],
        ),
    ]
