# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdaptivePlanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptive',
            name='Release',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
