# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdaptivePlanning', '0002_adaptive_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptive',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
