# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdaptivePlanning', '0003_adaptive_is_clicked'),
    ]

    operations = [
        migrations.CreateModel(
            name='pk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Release', models.IntegerField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='adaptive',
            name='Release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdaptivePlanning.pk'),
        ),
    ]
