# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdaptivePlanning', '0004_auto_20170912_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='pk',
            name='name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
