# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdaptivePlanning', '0006_adaptive1'),
    ]

    operations = [
        migrations.CreateModel(
            name='pk1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Release', models.IntegerField(max_length=250)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='adaptive1',
            name='Release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdaptivePlanning.pk1'),
        ),
    ]
